### ISSUE TITLE
Generating and loading Kernel modules

### ISSUE THREAD

**Issue by alexus1211** [raspberry-vanilla/android_kernel_manifest#1]
Hi,

I am trying to build the Kernel for RPI4 with support for the DHT11 temperature and humidity sensor.
first I tried to build the module statically with `CONFIG_DHT11=y` set. I can see from the build log that the driver has been built successfully:

> CC      drivers/iio/humidity/dht11.o

But after replacing the newer Kernel in the /boot partition, applying the `dht11-overlay` in config.txt and booting up Android14, I wasn't able to find any devices under `/sys/bus/iio/device*....`
I am not sure what is going wrong there. Maybe this is related to the GKI Kernel being used.

Furthermore, I tried to build it with `CONFIG_DHT11=m`, I am not able to find any `.ko` file getting generated. I plan to let Android load the DHT11 module on startup following this guide from [android source](https://source.android.com/docs/core/architecture/kernel/loadable-kernel-modules?hl=en).
Any support is appreciated.

**Comment by KonstaT** [comment]
Looking at the `dht11-overlay`, it also requires `iio-hwmon` driver (https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/arch/arm/boot/dts/overlays/dht11-overlay.dts#L23) which is not enabled (https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/arch/arm64/configs/android_rpi4_defconfig#L3134). Otherwise there shouldn't be any issue with this.

This is not an Android GKI (Generic Kernel Image). It's very much Raspberry Pi specific.

**Comment by alexus1211** [comment]
Thanks KonstaT, that solved the issue.
Furthermore I am currently experimenting with kernel modules. I am now able to build the DHT11 as module simply by setting  `CONFIG_DHT11=m` and adding _modules_ keyword to the `MAKE_GOALS` variable in _build.config.rpi4_:
```
MAKE_GOALS="
Image
dtbs
modules
"
```
I can confirm now that the _DHT11.ko_ module is getting generated. Now I need to modify Android to be able to load this module from the Vendor partition during init. I shall report on updates to this in a couple of weeks.

Again, many thanks

**Comment by KonstaT** [comment]
Since Raspberry Pi doesn't use GKI kernel (generic image that Google provides), there's really no reason to have any of the  device specific drivers as modules either.

Just compile the drivers directly into the kernel Image (i.e. `CONFIG_DHT11=y` & `CONFIG_SENSORS_IIO_HWMON=y`).

**Comment by KonstaT** [comment]
Closing as there hasn't been any activity in a month and should be resolved as above.
