### ISSUE TITLE
Compression method

### ISSUE THREAD

**Issue by alemig97** [raspberry-vanilla/android_kernel_manifest#13]
Hello Konsta, I wanted to make a comparison of the different methods of kernel compression/decompression, and by adding the compression configuration to android_rpi4_defconfig (CONFIG_KERNEL_GZIP), I can't seem to have it on config.gz on Raspberry Pi. Additional the size of image remains the same. How is it possible?

_Originally posted by @alemig97 in https://github.com/raspberry-vanilla/android_kernel_manifest/issues/11#issuecomment-2149422532_

**Comment by KonstaT** [comment]
It likely depends on something that you haven't enabled and/or is already enabled by default (https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/init/Kconfig#L230-L356).

You're of course welcome to experiment with different compression methods but in practice the boot partition size doesn't constraint the kernel image size and compression likely has some impact on RAM and CPU cycles.

**Comment by alemig97** [comment]
I enabled the CONFIG_HAVE_KERNEL_XZ and CONFIG_KERNEL_XZ configurations, but they do not appear to be active in the config.gz file after building. Also image in bazel-bin/boot/ is always Image (no .xz). Do other configurations need to be enabled? It shouldn’t have any other dependencies.

**Comment by alemig97** [comment]
No luck, is there something I can do to test the different algorithms compression?

**Comment by KonstaT** [comment]
https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/BUILD.bazel#L1089
https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/arch/arm64/boot/Makefile#L19-L40

There's indication that the Raspberry Pi bootloader firmware only supports decompressing gzipped kernel images in addition to the uncompressed format.
https://forums.raspberrypi.com/viewtopic.php?t=315445
https://github.com/raspberrypi/firmware/issues/1467

You're welcome investigate differences between `zImage`, `Image`, and `Image.gz` kernel formats. Using the compressed `zImage` format would likely indicate 32-bit and something old and outdated.

**Comment by alemig97** [comment]
So I change the configuration from Android_rpi4_defconf, adding those for gzip compression, and can I build the usual command directly? Do I need to add anything else?

**Comment by alemig97** [comment]
Thank you, I will try it. Instead, can the ramdisk.img be compressed only with gzip if all supported algorithms are activated in the configuration? Is it possible to change the algorithm and then update the bootloader in config.txt in the /boot directory?

**Comment by alemig97** [comment]
I tried using Image.gz (after building it with the command gzip Image, because the Bazel build and the configuration activated in android_rpi4_defconfig only produced an uncompressed Image) and copied the file to the /boot directory (after modifying config.txt), but I didn’t see any improvements in boot time. Is this possible?

**Comment by KonstaT** [comment]
With the bootloader firmware having to do something extra (decompressing the kernel image), one would expect the boot time to be longer?
