### ISSUE TITLE
compression

### ISSUE THREAD

**Issue by alemig97** [raspberry-vanilla/android_kernel_manifest#14]
I enabled the CONFIG_HAVE_KERNEL_XZ and CONFIG_KERNEL_XZ configurations, but they do not appear to be active in the config.gz file after building. Also image in bazel-bin/boot/ is always Image (no .xz). Do other configurations need to be enabled? It shouldn’t have any other dependencies.

_Originally posted by @alemig97 in https://github.com/raspberry-vanilla/android_kernel_manifest/issues/13#issuecomment-2159002411_

**Comment by KonstaT** [comment]
If I'd have something to add, I would do so in the previous issue.
