### ISSUE TITLE
Where to report bugs to KonstaKANG?

### ISSUE THREAD

**Issue by NiQ1** [raspberry-vanilla/android_kernel_manifest#15]
Sorry for using this platform but I can't find anywhere else to ask...
I have numerous bug reports for KonstaKANG's Android TV for RPi. They include not being able to set static IP address (you can input the address but there's no save button), not being able to add secondary keyboard languages (settings are not saved) etc.
Anyway it's not kernel but I can't seem to find any appropriate place to report them. If someone does please give me a link.

Thank you.

**Comment by KonstaT** [comment]
For your own builds from Raspberry Vanilla sources, as stated in the wiki:
Issues:
[Android](https://github.com/raspberry-vanilla/android_local_manifest/issues)
[Linux kernel](https://github.com/raspberry-vanilla/android_kernel_manifest/issues)

For my personal builds, you would reports issues on the release page of the build.

Neither of these seem specific to Raspberry Pi device specific device implementation but rather issues/feature requests regarding AOSP in general.

**Comment by NiQ1** [comment]
> For your own builds from Raspberry Vanilla sources, as stated in the wiki: Issues: [Android](https://github.com/raspberry-vanilla/android_local_manifest/issues) [Linux kernel](https://github.com/raspberry-vanilla/android_kernel_manifest/issues)
> 
> For my personal builds, you would reports issues on the release page of the build.
> 
> Neither of these seem specific to Raspberry Pi device specific device implementation but rather issues/feature requests regarding AOSP in general.

OK posted on the release page. Thank you.
