### ISSUE TITLE
ADB doesn't work

### ISSUE THREAD

**Issue by demoa00** [raspberry-vanilla/android_kernel_manifest#16]
Hello,
the configuration I am using is for Android 14 for Automotive on Raspberry Pi 4. I am not able to access ADB in any way and therefore I have no way of being able to read the logs coming from the Raspberry. I also tried with the serial port and SSH but nothing there is no way to be able to connect to the Raspberry. Are these tools included in your project or not?

**Comment by KonstaT** [comment]
You can use ADB over network or on the USB-C port.
On Pi 4 you can use serial console on GPIO14/15.
SSH support is not included in Raspberry Vanilla project but you can look into implementing e.g. https://github.com/lineage-rpi/android_external_openssh/tree/lineage-21.

Closing as this not an issue with Linux kernel at least.

**Comment by demoa00** [comment]
Sorry and thanks for the answer
