### ISSUE TITLE
Does support request_firmware?

### ISSUE THREAD

**Issue by xulinkun** [raspberry-vanilla/android_kernel_manifest#2]
Hi, KonstaT, I have a require that load firmware file by "request_firmware" api. Does support it? If yes, where is the firmware stored. (Usually it is stored under "vendor/firmware", but it is not in rpi5)

**Comment by KonstaT** [comment]
Wifi and bluetooth firmware is compiled into the kernel image.
https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/arch/arm64/configs/android_rpi5_defconfig#L1645-L1646

**Comment by xulinkun** [comment]
Actually, I need to verify various functions of touchscreen devices (include fw upgrade), I'm a Goodix's worker. So, Can you give me some advice about loading firmware?

**Comment by KonstaT** [comment]
Supporting the built-in hardware on Raspberry is what I'm concerned in the scope of this project.

How Android init manages mounting partition, vendor partition is not mounted at the point the kernel is loaded (i.e. no access to something that is on /vendor). If an approach where e.g. wifi/bluetooth drivers were compiled into modules loaded from the vendor partition at later stage, it could be possible to load the firmware from vendor as well. On my kernel I've taken an approach where all the drivers are compiled into the kernel Image and there is no modules. This way the firmware needs to be in the kernel Image or contained in the ramdisk.img.

You can try adding firmware files as above. You can also try setting e.g. `firmware_class.path=/vendor/etc/firmware` on kernel cmdline if that helps loading firmware files from vendor partition.

The flow chart on https://wiki.tizen.org/Usage_and_Mechanism_of_kernel_function_%22request_firmware()%22 seems accurate at least. To be able to update the firmware using sysfs, you would need to compile the kernel with `CONFIG_FW_UPLOAD` enabled (https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-14.0/arch/arm64/configs/android_rpi5_defconfig#L1650).

**Comment by xulinkun** [comment]
I follow your advice, add `firmware_class.path=/vendor/etc/firmware` and `mkdir /vendor/etc/firmware` manually, then all things ok, thanks lot.
