### ISSUE TITLE
Which usb port is used for adb ?

### ISSUE THREAD

**Issue by tonyho** [raspberry-vanilla/android_kernel_manifest#20]
I notice in the config.txt file, there is a line :

```
dtoverlay=dwc2,dr_mode=peripheral
```

Is there an USB port for adb?  If so, which one?

**Comment by KonstaT** [comment]
Yes, that configures the USB-C port. ADB, MTP, PTP, and USB tethering tethering are supported on the USB-C port. You'll need powered USB-C hub or 5V on the GPIO. Regular USB-A ports on the Pi are host mode only.
