### ISSUE TITLE
Getting error while repo sync

### ISSUE THREAD

**Issue by Parth414** [raspberry-vanilla/android_kernel_manifest#3]
[Cannot fetch raspberry-vanilla/android_external_wpa_supplicant_8 from https://github.com/raspberry-vanilla/android_external_wpa_supplicant_8](error: Cannot fetch raspberry-vanilla/android_external_wpa_supplicant_8 from https://github.com/raspberry-vanilla/android_external_wpa_supplicant_8)

**Comment by KonstaT** [comment]
`wpa_supplicant_8` is not part of the kernel build environment where you're commenting. https://github.com/raspberry-vanilla/android_local_manifest would be the correct place.

If you synced the the AOSP source code sometime before `wpa_supplicant_8` was forked to Raspberry Vanilla project and added to the local manifest, you can `repo sync --force-sync external/wpa_supplicant_8` as it's also suggested in the actual error message.
