### ISSUE TITLE
Can't connect Bluetooth controller (PS4) 

### ISSUE THREAD

**Issue by ouroboros420** [raspberry-vanilla/android_kernel_manifest#5]
Right at the setup of the rpi5 with android TV Los 21 I tried connecting a Bluetooth controller. Interestingly my remote worked straight away, though I'm not sure if through the pi or the through my Sony android TV that was able to communicate. 
So searching for the PS4 controller. It gets shown, but pressing it just stays for ever in pairing mode, it never fully connects. Is a bummer because I hoped at least through android I'll be able to play some PS2,  but nah lol

**Comment by KonstaT** [comment]
Nah, LOL. Wrong place, wrong format.

This issue tracker is intended for issues in AOSP builds from Raspberry Vanilla source code, and issues with Linux kernel specifically. Since I don't have the hardware to reproduce the issue and there's no logs attached, there's nothing I can do.
