### ISSUE TITLE
Error in Building Kernel for Raspberry Pi 4

### ISSUE THREAD

**Issue by Helena2816** [raspberry-vanilla/android_kernel_manifest#7]
I attempted to build the kernel for raspberry pi 4 using the command BUILD_CONFIG=common/build.config.rpi4 build/build.sh, but encountered several linker errors. I hadn't made any changes to the codebase, I attempted the build immediately after successfully syncing the repository. Here's the error output from the terminal :
Inferring equivalent Bazel command...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: No matching copy_to_dist_dir targets depend on the given build config.
*****************************************************************************
* WARNING: build.sh is deprecated for this branch. Please migrate to Bazel.  
*   See build/kernel/kleaf/README.md                                         
WARNING: Unable to infer an equivalent Bazel command.                        
* To suppress this warning, set KLEAF_SUPPRESS_BUILD_SH_DEPRECATION_WARNING=1
*****************************************************************************

========================================================
 Setting up for build
+ cd common
+ make LLVM=1 DEPMOD=depmod DTC=/media/trainee/DATA/kernel/common-android13-5.15-lts/build/kernel/build-tools/path/linux-x86/dtc O=/media/trainee/DATA/kernel/common-android13-5.15-lts/out/common mrproper
make[1]: Entering directory '/media/trainee/DATA/kernel/common-android13-5.15-lts/out/common'
make[1]: Leaving directory '/media/trainee/DATA/kernel/common-android13-5.15-lts/out/common'
+ set +x
+ cd common
+ make LLVM=1 DEPMOD=depmod DTC=/media/trainee/DATA/kernel/common-android13-5.15-lts/build/kernel/build-tools/path/linux-x86/dtc O=/media/trainee/DATA/kernel/common-android13-5.15-lts/out/common android_rpi4_defconfig
make[1]: Entering directory '/media/trainee/DATA/kernel/common-android13-5.15-lts/out/common'
  GEN     Makefile
  HOSTCC  scripts/basic/fixdep
ld.lld: error: undefined symbol: __libc_csu_fini
>>> referenced by /media/trainee/DATA/kernel/common-android13-5.15-lts/build/kernel/build-tools/sysroot/usr/lib/crt1.o:(.text+0x12)

ld.lld: error: undefined symbol: __libc_csu_init
>>> referenced by /media/trainee/DATA/kernel/common-android13-5.15-lts/build/kernel/build-tools/sysroot/usr/lib/crt1.o:(.text+0x19)

ld.lld: error: undefined symbol: __libc_start_main
>>> referenced by /media/trainee/DATA/kernel/common-android13-5.15-lts/build/kernel/build-tools/sysroot/usr/lib/crt1.o:(.text+0x25)

ld.lld: error: undefined symbol: printf
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced 4 more times

ld.lld: error: undefined symbol: strstr
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)

ld.lld: error: undefined symbol: __ctype_b_loc
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)

ld.lld: error: undefined symbol: bcmp
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)

ld.lld: error: undefined symbol: malloc
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(read_file)

ld.lld: error: undefined symbol: memcpy
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)

ld.lld: error: undefined symbol: free
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)

ld.lld: error: undefined symbol: stdout
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)

ld.lld: error: undefined symbol: fflush
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)

ld.lld: error: undefined symbol: ferror
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)

ld.lld: error: undefined symbol: perror
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(read_file)

ld.lld: error: undefined symbol: exit
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(read_file)

ld.lld: error: undefined symbol: stderr
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced 2 more times

ld.lld: error: undefined symbol: fwrite
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(main)
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(read_file)

ld.lld: error: undefined symbol: open
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(read_file)

ld.lld: error: undefined symbol: __fxstat
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(read_file)

ld.lld: error: undefined symbol: read
>>> referenced by fixdep.c
>>>               /tmp/fixdep-c5698e.o:(read_file)

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/media/trainee/DATA/kernel/common-android13-5.15-lts/common/scripts/Makefile.host:111: scripts/basic/fixdep] Error 1
make[1]: *** [/media/trainee/DATA/kernel/common-android13-5.15-lts/common/Makefile:658: scripts_basic] Error 2
make[1]: Leaving directory '/media/trainee/DATA/kernel/common-android13-5.15-lts/out/common'
make: *** [Makefile:256: __sub-make] Error 2

**Comment by KonstaT** [comment]
What Linux distro are you using? Most likely something related to your build environment. Have installed the required packages?
https://source.android.com/docs/setup/start/requirements#install-packages

**Comment by Helena2816** [comment]
I am using Ubuntu 22.04.4 LTS, and I have already installed all the necessary packages. Additionally, I want to mention that two months ago, I successfully built it with the same environment.

**Comment by KonstaT** [comment]
What branch have you synced? `android-14.0` assuming from the `android_rpi4_defconfig` despite the `common-android13-5.15-lts` directory?

Try to trace your own steps. There hasn't been any changes in the kernel build environment in last two months that would explain this.

**Comment by Helena2816** [comment]
I synced the Android-14.0 branch and followed the steps provided in the readme. I didn't change anything, except the previous build was done on the disk where the system is installed, whereas now I'm attempting to build it on a storage disk.

**Comment by KonstaT** [comment]
Is the drive formatted to a Linux filesystem (`ext4`)? Windows filesystems (`NTFS`, etc) probably can't handle this.

Use a storage device that's formatted to `ext4`.

**Comment by Helena2816** [comment]
yes the storage disk is formatted with the ext4 file system

**Comment by KonstaT** [comment]
`android-14.0` branch has just migrated to new build system. Please sync your sources again following the updated instructions.
https://github.com/raspberry-vanilla/android_kernel_manifest/tree/android-14.0

**Comment by Helena2816** [comment]
I successfully built and tested it.
